#eureka config
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

#actuator Config
management:
  endpoint:
    web:
        exposure:
            include: "*"

#Zipkins Config
  tracing:
    sampling:
          probability: 1.0

spring:
  zipkin:
    base-url: http://localhost:9411
